name: 빌드 자동화

on:
  push:
    branches:
      - main
      - feat/cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (언어 환경)
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Create .env.production file
        run: |
          echo "NODE_ENV=production" > .env.production 
          echo "MODE=production" >> .env.production  
          echo "VITE_GA_MEASUREMENT_ID=${{ secrets.VITE_GA_MEASUREMENT_ID }}" >> .env.production

      - name: Install dependencies
        run: npm ci

      - name: Run build
        env:
          NODE_ENV: production
        run: npm run build -- --mode production

      - name: Verify Build Mode
        run: |
          grep -r "production" dist/assets/*.js | grep "import.meta.env.MODE"

      - name: Debug .env.production file
        run: cat .env.production || echo ".env.production not found"

      - name: Verify Build Mode in Output Files
        run: grep -r "import.meta.env" dist/ || echo "No env variables found in built files"

      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/embitips_front .
          docker push ${{ secrets.DOCKER_USERNAME }}/embitips_front

      - name: Deploy to GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker stop embitips_front || true
            sudo docker rm embitips_front || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/embitips_front
            sudo docker run -d -p 3000:3000 --name embitips_front ${{ secrets.DOCKER_USERNAME }}/embitips_front
            sudo docker image prune -f
